// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package access_point

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/efs"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/efs/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/efs-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.AccessPoint{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	input.FileSystemId = nil
	var resp *svcsdk.DescribeAccessPointsOutput
	resp, err = rm.sdkapi.DescribeAccessPoints(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeAccessPoints", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "AccessPointNotFound" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.AccessPoints {
		if elem.AccessPointArn != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.AccessPointArn)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.AccessPointId != nil {
			ko.Status.AccessPointID = elem.AccessPointId
		} else {
			ko.Status.AccessPointID = nil
		}
		if elem.FileSystemId != nil {
			ko.Spec.FileSystemID = elem.FileSystemId
		} else {
			ko.Spec.FileSystemID = nil
		}
		if elem.LifeCycleState != "" {
			ko.Status.LifeCycleState = aws.String(string(elem.LifeCycleState))
		} else {
			ko.Status.LifeCycleState = nil
		}
		if elem.Name != nil {
			ko.Status.Name = elem.Name
		} else {
			ko.Status.Name = nil
		}
		if elem.OwnerId != nil {
			ko.Status.OwnerID = elem.OwnerId
		} else {
			ko.Status.OwnerID = nil
		}
		if elem.PosixUser != nil {
			f6 := &svcapitypes.PosixUser{}
			if elem.PosixUser.Gid != nil {
				f6.GID = elem.PosixUser.Gid
			}
			if elem.PosixUser.SecondaryGids != nil {
				f6.SecondaryGIDs = aws.Int64Slice(elem.PosixUser.SecondaryGids)
			}
			if elem.PosixUser.Uid != nil {
				f6.UID = elem.PosixUser.Uid
			}
			ko.Spec.PosixUser = f6
		} else {
			ko.Spec.PosixUser = nil
		}
		if elem.RootDirectory != nil {
			f7 := &svcapitypes.RootDirectory{}
			if elem.RootDirectory.CreationInfo != nil {
				f7f0 := &svcapitypes.CreationInfo{}
				if elem.RootDirectory.CreationInfo.OwnerGid != nil {
					f7f0.OwnerGID = elem.RootDirectory.CreationInfo.OwnerGid
				}
				if elem.RootDirectory.CreationInfo.OwnerUid != nil {
					f7f0.OwnerUID = elem.RootDirectory.CreationInfo.OwnerUid
				}
				if elem.RootDirectory.CreationInfo.Permissions != nil {
					f7f0.Permissions = elem.RootDirectory.CreationInfo.Permissions
				}
				f7.CreationInfo = f7f0
			}
			if elem.RootDirectory.Path != nil {
				f7.Path = elem.RootDirectory.Path
			}
			ko.Spec.RootDirectory = f7
		} else {
			ko.Spec.RootDirectory = nil
		}
		if elem.Tags != nil {
			f8 := []*svcapitypes.Tag{}
			for _, f8iter := range elem.Tags {
				f8elem := &svcapitypes.Tag{}
				if f8iter.Key != nil {
					f8elem.Key = f8iter.Key
				}
				if f8iter.Value != nil {
					f8elem.Value = f8iter.Value
				}
				f8 = append(f8, f8elem)
			}
			ko.Spec.Tags = f8
		} else {
			ko.Spec.Tags = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	if !accessPointActive(&resource{ko}) {
		return &resource{ko}, requeueWaitState(r)
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return r.ko.Status.AccessPointID == nil

}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeAccessPointsInput, error) {
	res := &svcsdk.DescribeAccessPointsInput{}

	if r.ko.Status.AccessPointID != nil {
		res.AccessPointId = r.ko.Status.AccessPointID
	}
	if r.ko.Spec.FileSystemID != nil {
		res.FileSystemId = r.ko.Spec.FileSystemID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}
	// This is an idempotency token required in the API call...
	input.ClientToken = aws.String(getIdempotencyToken())

	var resp *svcsdk.CreateAccessPointOutput
	_ = resp
	resp, err = rm.sdkapi.CreateAccessPoint(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateAccessPoint", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.AccessPointArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.AccessPointArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.AccessPointId != nil {
		ko.Status.AccessPointID = resp.AccessPointId
	} else {
		ko.Status.AccessPointID = nil
	}
	if resp.FileSystemId != nil {
		ko.Spec.FileSystemID = resp.FileSystemId
	} else {
		ko.Spec.FileSystemID = nil
	}
	if resp.LifeCycleState != "" {
		ko.Status.LifeCycleState = aws.String(string(resp.LifeCycleState))
	} else {
		ko.Status.LifeCycleState = nil
	}
	if resp.Name != nil {
		ko.Status.Name = resp.Name
	} else {
		ko.Status.Name = nil
	}
	if resp.OwnerId != nil {
		ko.Status.OwnerID = resp.OwnerId
	} else {
		ko.Status.OwnerID = nil
	}
	if resp.PosixUser != nil {
		f6 := &svcapitypes.PosixUser{}
		if resp.PosixUser.Gid != nil {
			f6.GID = resp.PosixUser.Gid
		}
		if resp.PosixUser.SecondaryGids != nil {
			f6.SecondaryGIDs = aws.Int64Slice(resp.PosixUser.SecondaryGids)
		}
		if resp.PosixUser.Uid != nil {
			f6.UID = resp.PosixUser.Uid
		}
		ko.Spec.PosixUser = f6
	} else {
		ko.Spec.PosixUser = nil
	}
	if resp.RootDirectory != nil {
		f7 := &svcapitypes.RootDirectory{}
		if resp.RootDirectory.CreationInfo != nil {
			f7f0 := &svcapitypes.CreationInfo{}
			if resp.RootDirectory.CreationInfo.OwnerGid != nil {
				f7f0.OwnerGID = resp.RootDirectory.CreationInfo.OwnerGid
			}
			if resp.RootDirectory.CreationInfo.OwnerUid != nil {
				f7f0.OwnerUID = resp.RootDirectory.CreationInfo.OwnerUid
			}
			if resp.RootDirectory.CreationInfo.Permissions != nil {
				f7f0.Permissions = resp.RootDirectory.CreationInfo.Permissions
			}
			f7.CreationInfo = f7f0
		}
		if resp.RootDirectory.Path != nil {
			f7.Path = resp.RootDirectory.Path
		}
		ko.Spec.RootDirectory = f7
	} else {
		ko.Spec.RootDirectory = nil
	}
	if resp.Tags != nil {
		f8 := []*svcapitypes.Tag{}
		for _, f8iter := range resp.Tags {
			f8elem := &svcapitypes.Tag{}
			if f8iter.Key != nil {
				f8elem.Key = f8iter.Key
			}
			if f8iter.Value != nil {
				f8elem.Value = f8iter.Value
			}
			f8 = append(f8, f8elem)
		}
		ko.Spec.Tags = f8
	} else {
		ko.Spec.Tags = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateAccessPointInput, error) {
	res := &svcsdk.CreateAccessPointInput{}

	if r.ko.Spec.FileSystemID != nil {
		res.FileSystemId = r.ko.Spec.FileSystemID
	}
	if r.ko.Spec.PosixUser != nil {
		f1 := &svcsdktypes.PosixUser{}
		if r.ko.Spec.PosixUser.GID != nil {
			f1.Gid = r.ko.Spec.PosixUser.GID
		}
		if r.ko.Spec.PosixUser.SecondaryGIDs != nil {
			f1.SecondaryGids = aws.ToInt64Slice(r.ko.Spec.PosixUser.SecondaryGIDs)
		}
		if r.ko.Spec.PosixUser.UID != nil {
			f1.Uid = r.ko.Spec.PosixUser.UID
		}
		res.PosixUser = f1
	}
	if r.ko.Spec.RootDirectory != nil {
		f2 := &svcsdktypes.RootDirectory{}
		if r.ko.Spec.RootDirectory.CreationInfo != nil {
			f2f0 := &svcsdktypes.CreationInfo{}
			if r.ko.Spec.RootDirectory.CreationInfo.OwnerGID != nil {
				f2f0.OwnerGid = r.ko.Spec.RootDirectory.CreationInfo.OwnerGID
			}
			if r.ko.Spec.RootDirectory.CreationInfo.OwnerUID != nil {
				f2f0.OwnerUid = r.ko.Spec.RootDirectory.CreationInfo.OwnerUID
			}
			if r.ko.Spec.RootDirectory.CreationInfo.Permissions != nil {
				f2f0.Permissions = r.ko.Spec.RootDirectory.CreationInfo.Permissions
			}
			f2.CreationInfo = f2f0
		}
		if r.ko.Spec.RootDirectory.Path != nil {
			f2.Path = r.ko.Spec.RootDirectory.Path
		}
		res.RootDirectory = f2
	}
	if r.ko.Spec.Tags != nil {
		f3 := []svcsdktypes.Tag{}
		for _, f3iter := range r.ko.Spec.Tags {
			f3elem := &svcsdktypes.Tag{}
			if f3iter.Key != nil {
				f3elem.Key = f3iter.Key
			}
			if f3iter.Value != nil {
				f3elem.Value = f3iter.Value
			}
			f3 = append(f3, *f3elem)
		}
		res.Tags = f3
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return rm.customUpdateAccessPoint(ctx, desired, latest, delta)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteAccessPointOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteAccessPoint(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteAccessPoint", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteAccessPointInput, error) {
	res := &svcsdk.DeleteAccessPointInput{}

	if r.ko.Status.AccessPointID != nil {
		res.AccessPointId = r.ko.Status.AccessPointID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.AccessPoint,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
