// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package replication_configuration

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if len(a.ko.Spec.Destinations) != len(b.ko.Spec.Destinations) {
		delta.Add("Spec.Destinations", a.ko.Spec.Destinations, b.ko.Spec.Destinations)
	} else if len(a.ko.Spec.Destinations) > 0 {
		if !reflect.DeepEqual(a.ko.Spec.Destinations, b.ko.Spec.Destinations) {
			delta.Add("Spec.Destinations", a.ko.Spec.Destinations, b.ko.Spec.Destinations)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.SourceFileSystemID, b.ko.Spec.SourceFileSystemID) {
		delta.Add("Spec.SourceFileSystemID", a.ko.Spec.SourceFileSystemID, b.ko.Spec.SourceFileSystemID)
	} else if a.ko.Spec.SourceFileSystemID != nil && b.ko.Spec.SourceFileSystemID != nil {
		if *a.ko.Spec.SourceFileSystemID != *b.ko.Spec.SourceFileSystemID {
			delta.Add("Spec.SourceFileSystemID", a.ko.Spec.SourceFileSystemID, b.ko.Spec.SourceFileSystemID)
		}
	}
	if !reflect.DeepEqual(a.ko.Spec.SourceFileSystemRef, b.ko.Spec.SourceFileSystemRef) {
		delta.Add("Spec.SourceFileSystemRef", a.ko.Spec.SourceFileSystemRef, b.ko.Spec.SourceFileSystemRef)
	}

	return delta
}
