---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-efs-reader
  namespace: default
rules:
- apiGroups:
  - efs.services.k8s.aws
  resources:
  - accesspoints
  - filesystems
  - mounttargets
  - replicationconfigurations
  verbs:
  - get
  - list
  - watch
